services:
  # The Spring Boot Gateway
  - type: web
    name: inferx-gateway
    env: docker
    dockerContext: ./inferx-gateway
    dockerfilePath: ./inferx-gateway/Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATA_REDIS_HOST
        sync: false # Paste your Upstash Redis Host here (just the hostname, NO https://)
      - key: SPRING_DATA_REDIS_PORT
        sync: false # Paste your Upstash Redis Port here (usually 6379)
      - key: SPRING_DATA_REDIS_PASSWORD
        sync: false # Paste your Upstash Redis Password here
      - key: SPRING_DATA_REDIS_SSL_ENABLED
        value: "true"
      - key: SERVER_PORT
        value: "10000"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx256m -Xms256m"

  # The PyTorch Worker (Faking a web service for the free tier!)
  - type: web
    name: inferx-worker
    env: docker
    dockerContext: ./inferx-worker
    dockerfilePath: ./inferx-worker/Dockerfile
    plan: free
    envVars:
      - key: REDIS_HOST
        sync: false 
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: "true"
